version: '3'

services:

  veiculo-db:
    container_name: veiculo-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: veiculodb
      POSTGRES_DB: veiculodb
      POSTGRES_PASSWORD: veiculodb